name: smooth_animated_button_package
description: This is smooth animated button package.
version: 0.0.4
homepage: https://github.com/NurhayatYurtaslan/smooth_animated_button_press
documentation: https://github.com/NurhayatYurtaslan/smooth_animated_button_press/blob/main/README.md

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
